environments:
  dev:  # Required - Environment name
    accounts:  # Required - At least one account
      account1: "298841451579"  # Required - 12-digit AWS account ID
    region: "us-east-1"  # Required - AWS region
    
    vpc:  # Required - VPC configuration
      id: "vpc-0049bd60883924128"  # Required - VPC ID
      private_subnet_ids:  # Required - At least 2 private subnets
        - "subnet-03c8284b2c66d21b6"  # us-east-1a
        - "subnet-054ebd91e1ac2b16f"  # us-east-1b

    # Optional - Redshift configuration
    # redshift:
    #   cluster_identifier: "deckers-brands-poc-redhisft-cluster"  # Required if redshift section present
    #   database_name: "dev_db"  # Required if redshift section present
    #   port: 5439  # Optional
    #   endpoint: "deckers-brands-poc-redhisft-cluster.c40cimxkq3nk.us-east-1.redshift.amazonaws.com:5439/dev"  # Optional

    mwaa:  # Required - MWAA configuration
      name: "decker-cdk-mwaa-test"  # Required - Environment name
      endpoint_management: "CUSTOMER"  # Optional - Defaults to "SERVICE"
      dags_s3_bucket: "decker-cdk-mwaa-test-dags-sadfjligajsdgasd"  # Required - S3 bucket name
      dags_folder: "dags"  # Required - S3 path for DAGs
      requirements_file: "requirements/requirements.txt"  # Optional - Path to requirements file
      plugins_file: "plugins/plugins.zip"  # Optional - Path to plugins zip
      startup_script_file: "startup.sh"  # Optional - Startup script
      airflow_version: "2.10.3"  # Required - Airflow version
      environment_class: "mw1.small"  # Required - Environment class
      min_workers: 1  # Required - Minimum workers
      max_workers: 5  # Required - Maximum workers
      schedulers: 2  # Optional - Number of schedulers
      webserver_access_mode: "PRIVATE_ONLY"  # Required - PUBLIC_ONLY or PRIVATE_ONLY
      weekly_maintenance_window_start: "SUN:03:00"  # Optional - Maintenance window
      
      # Optional - Logging configuration
      # logging:
      #   Task:
      #     enabled: true
      #     log_level: "INFO"
      #   WebServer:
      #     enabled: true
      #     log_level: "INFO"
      #   Scheduler:
      #     enabled: true
      #     log_level: "INFO"
      #   Worker:
      #     enabled: true
      #     log_level: "INFO"
      #   DAGProcessing:
      #     enabled: true
      #     log_level: "INFO"
      
      # Optional - Airflow configuration options
      # airflow_configuration_options:
      #   "core.load_examples": "False"
      #   "core.dags_are_paused_at_creation": "False"
      #   "webserver.expose_config": "True"
      #   "webserver.instance_name": "decker-cdk-mwaa-test"
      #   "core.parallelism": "32"
      #   "core.dag_concurrency": "16"
      #   "core.max_active_runs_per_dag": "16"
      #   "scheduler.catchup_by_default": "False"
      #   "scheduler.dag_dir_list_interval": "300"
      #   "webserver.rbac": "True"
      #   "webserver.dag_default_view": "tree"
      #   "webserver.dag_orientation": "TB"

    # Optional - Resource tags
    tags:
      ProjectID: "AWS-CCT-Developer"
      Email: "sanjay.jat@quantiphi.com"
      "Workday Project ID": "AWS-CCT-Developer"
      Environment: "dev"
      ManagedBy: "AWS-CDK"